#!/usr/bin/env python3
"""
snapshot_phase.py — freeze a phase's UI + graph composition into snapshots/.

Each phase ships a snapshot so the demo it shipped with can be replayed later
even after Phase N+1 changes things. The snapshot is a self-contained copy of
the phase-specific files; production code keeps evolving but snapshots are
read-only after `--phase N` is invoked.

Usage:
    python scripts/snapshot_phase.py --phase 1

What it copies:
    ui/phase{N}/                  → snapshots/phase{N}/ui/
    pipeline/graph_v{N}.py        → snapshots/phase{N}/graph_v{N}.py
    MANIFEST_PHASE_{N}.md         → snapshots/phase{N}/MANIFEST.md

After Phase 4 ships, `snapshots/phase1/`, `phase2/`, `phase3/`, `phase4/`
each give a frozen view of how the system looked at that phase's git tag
(v1.0-phase1 / v2.0-phase2 / ...).
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
from pathlib import Path

# Make repo-root imports work regardless of cwd.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

logger = logging.getLogger("snapshot_phase")


# ---------------------------------------------------------------------------
# Snapshot logic
# ---------------------------------------------------------------------------


def snapshot_phase(phase: int, *, force: bool = False, dry_run: bool = False) -> int:
    """Copy a phase's UI + graph + manifest into snapshots/phaseN/.

    Returns 0 on success, non-zero on error.
    """
    repo = _REPO_ROOT
    ui_src = repo / "ui" / f"phase{phase}"
    graph_src = repo / "pipeline" / f"graph_v{phase}.py"
    manifest_src = repo / f"MANIFEST_PHASE_{phase}.md"

    snapshot_dir = repo / "snapshots" / f"phase{phase}"
    ui_dst = snapshot_dir / "ui"
    graph_dst = snapshot_dir / f"graph_v{phase}.py"
    manifest_dst = snapshot_dir / "MANIFEST.md"

    # ----- Pre-flight checks -----
    missing: list[Path] = []
    for src in (graph_src, manifest_src):
        if not src.exists():
            missing.append(src)
    # UI is optional (Phase 1 may snapshot before the UI is wired); warn but don't fail.
    if not ui_src.exists():
        logger.warning("UI source not found: %s (continuing; UI may not be built yet)", ui_src)

    if missing:
        for m in missing:
            print(f"ERROR: required source missing: {m}", file=sys.stderr)
        return 2

    if snapshot_dir.exists() and not force:
        print(
            f"ERROR: snapshot already exists at {snapshot_dir} — re-run with "
            f"--force to overwrite, or `rm -rf {snapshot_dir}` first.",
            file=sys.stderr,
        )
        return 3

    if dry_run:
        print("Dry-run plan:")
        print(f"  COPY DIR  {ui_src}  →  {ui_dst}")
        print(f"  COPY FILE {graph_src}  →  {graph_dst}")
        print(f"  COPY FILE {manifest_src}  →  {manifest_dst}")
        return 0

    # ----- Execute -----
    if snapshot_dir.exists() and force:
        logger.info("Removing existing %s (--force)", snapshot_dir)
        shutil.rmtree(snapshot_dir)
    snapshot_dir.mkdir(parents=True, exist_ok=True)

    files_copied = 0
    if ui_src.exists():
        shutil.copytree(ui_src, ui_dst)
        files_copied += sum(1 for _ in ui_dst.rglob("*") if _.is_file())
        logger.info("Copied UI tree:  %s  →  %s", ui_src, ui_dst)

    shutil.copyfile(graph_src, graph_dst)
    files_copied += 1
    logger.info("Copied graph:    %s  →  %s", graph_src, graph_dst)

    shutil.copyfile(manifest_src, manifest_dst)
    files_copied += 1
    logger.info("Copied manifest: %s  →  %s", manifest_src, manifest_dst)

    # Drop a README in the snapshot dir to explain what it is.
    readme = snapshot_dir / "README.md"
    readme.write_text(
        f"# Phase {phase} snapshot\n\n"
        f"Frozen copy of the Phase {phase} demo set. Generated by "
        f"`scripts/snapshot_phase.py --phase {phase}`.\n\n"
        f"Contents:\n"
        f"  - `ui/`          — the Phase {phase} Streamlit app, runnable as "
        f"`streamlit run snapshots/phase{phase}/ui/app.py`\n"
        f"  - `graph_v{phase}.py` — the frozen pipeline graph composition.\n"
        f"  - `MANIFEST.md`  — the Phase {phase} shipping manifest at the "
        f"time of the snapshot.\n\n"
        f"This directory is **read-only by convention** — Phase {phase+1}+ "
        f"work should not modify these files. The snapshot exists so the "
        f"Phase {phase} demo can be replayed after later phases ship.\n",
        encoding="utf-8",
    )
    files_copied += 1

    print(
        f"\n✓ Snapshot complete: {snapshot_dir}\n"
        f"  {files_copied} file(s) copied.\n"
        f"  Next: `git add snapshots/phase{phase}/ && git commit -m 'Phase {phase} snapshot'`",
    )
    return 0


# ---------------------------------------------------------------------------
# argparse + main
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Freeze a phase's UI + graph composition into snapshots/phaseN/.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--phase", type=int, required=True, choices=[1, 2, 3, 4],
        help="Which phase to snapshot.",
    )
    p.add_argument(
        "--force", action="store_true",
        help="Overwrite an existing snapshots/phaseN/ directory.",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Print the copy plan without writing anything.",
    )
    p.add_argument(
        "--verbose", "-v", action="store_true",
        help="Enable DEBUG logging.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv or sys.argv[1:])
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)-5s %(name)s — %(message)s",
        stream=sys.stderr,
    )
    return snapshot_phase(args.phase, force=args.force, dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
